### ISSUE TITLE
Please check the sorting before upping the version

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamori#353]
Nakamori auto updated, and Favorites and Recently Added Series/Episodes are at the top. "All" should always be the first item.

**Comment by bigretromike** [comment]
Nope. Favorite should be, then Recent then All. Use settings to disable both if you want All be on top. 

On August 18, 2019 6:58:02 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Nakamori auto updated, and Favorites and Recently Added Series/Episodes
>are at the top. "All" should always be the first item.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigretromike/nakamori/issues/353

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Favorite will always be on top (if enabled) to access favorite aka most important series
Recently Added (v2 if enabled) will be next because some want to watch the file they just added, this will be deleted when Shoko will fix its own api until then its on top
then there are filters 
calendars/settings - if enabled
and ALWAYS search will be last to quick access (aka arrow up on main menu)
