### ISSUE TITLE
Kodi 19

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamori#381]
Hey BRM, were getting asked about a Kodi 19 compatible version of Nakamori and was wondering if its in the works or if Nakamori will only work on Kodi 18 and below?

**Comment by bigretromike** [comment]
yes. I just patched quick and dirty version for Kodi19.

I will try to have it up and running in few hours.

After that I will be redoing it so everything will work as it used to.

**Comment by bigretromike** [comment]
@ElementalCrisis https://github.com/bigretromike/nakamori/releases/tag/3.6.0

**Comment by ElementalCrisis** [comment]
Oh awesome, I'll give it a go later today!

**Comment by bigretromike** [comment]
@ElementalCrisis 
It will work with pre 4.0-shokoserver - that was what I have installed.
But I need some time to make it work with newest version. 
Lots of things changes sice 3.9.x :-) but project is not dead

**Comment by ElementalCrisis** [comment]
No worries, let me know once its works with the latest version of Shoko and I'll make a blog post about it. :)

**Comment by kusco123** [comment]
Hello bigretromike - still working on this or to be considered dead?

**Comment by bigretromike** [comment]
@kusco123 hello, yeah stilling working. probably because I'm putting more time into work. I'm thinking about it once a week. 

Looks like I need to upgrade shoko server so I will finally have broken installation and bigger need to fix this.

In 2 weeks I will have paid vacations from work, so that will be a probably good idea to start digging into code.

**Comment by kusco123** [comment]
Cool - happy to see that it is still breathing :) 


> @kusco123 hello, yeah stilling working. probably because I'm putting more time into work. I'm thinking about it once a week.
> 
> Looks like I need to upgrade shoko server so I will finally have broken installation and bigger need to fix this.
> 
> In 2 weeks I will have paid vacations from work, so that will be a probably good idea to start digging into code.
> 
> Edit: Thanks for asking

Cool - happy to see that it is still breathing :)

**Comment by bigretromike** [comment]
@ElementalCrisis Hello. Thanks !
Besides building it from scratch for Kodi 19, it also is fully compatible with ShokoServer 4.1.x. 
Nothing to fancy - for now there is no change log, but surely there will be one, when I'm done with calendar.

**Comment by bigretromike** [comment]
Also I will be updating stable repository, as for now only dev one is up2date, so you can wait 2more days until I get around it and make it right @ElementalCrisis I didn't haste to inform you because I wanted to finish the 'old' stable repository so everyone that had been using it would get update - but I did not figure out how not to nuke them so I will probably make one new repository as for now we not using multiply modules just for one plugin :-)

**Comment by ElementalCrisis** [comment]
Sounds good! 

Send me a message on Discord when it's all ready to go! :)

**Comment by ElementalCrisis** [comment]
Hey BRM, just checking in and seeing how it's coming along.

**Comment by ElementalCrisis** [comment]
Sorry for the late response, I don't get notified apparently of replies and have been busy.

I'll make the blog post this week. Anything in particular you'd like me to mention in it?

**Comment by bigretromike** [comment]
@ElementalCrisis postpone that news, I would like to review code against newest shoko+kodi. No need to "announce" something that is not tested with latest v.

**Comment by ElementalCrisis** [comment]
No problem, I've been busy so haven't had a chance to type it out yet.

Let me know when you're ready.
